### ISSUE TITLE
Issue trying to put status color on card

### ISSUE THREAD

**Issue by nairdesigns** [abauville/lickwars#51]
i'm trying to update the status so that it changes according to color but i keep getting an error that says Exercise 3 doesn't have any music. does anyone know what the problem could be?

![image](https://user-images.githubusercontent.com/37412568/156526985-3b88090a-b6c9-419f-a435-49b9addcfb08.png)
![image](https://user-images.githubusercontent.com/37412568/156527122-24d0fdcb-8588-4904-8fe1-152df16b99ce.png)
![image](https://user-images.githubusercontent.com/37412568/156527234-09c4db72-8fcf-4d75-b9c0-4d175a7f4822.png)
so not all exercises have music?

**Comment by km111444** [comment]
Hi, Brian! sorry for this error. I found issues in seeds.rb and I will change that!

**Comment by abauville** [comment]
That's been solved in pull request #91
