### ISSUE TITLE
Issue with teacher button

### ISSUE THREAD

**Issue by abauville** [abauville/lickwars#73]
For some reason the js script for the teacher teacher button is triggered on every page, even if there is no button (e.g. homepage, exercise index and show). It doesn't cause a crash but there is a js error in the console every time we scroll. See below.

<img width="816" alt="Screen Shot 2022-03-05 at 18 37 36" src="https://user-images.githubusercontent.com/39847270/156877659-9c0b9814-b9d5-4d37-b77f-67c17d6805f6.png">
<img width="594" alt="Screen Shot 2022-03-05 at 18 39 17" src="https://user-images.githubusercontent.com/39847270/156877678-402d2708-50be-4bc5-9b5b-dcbfb2e888e9.png">

**Comment by markiecyt** [comment]
Just needs a conditional statement for if the button exists. Not sure the best place to do it though. Will need to rethink it a little 🤔

**Comment by abauville** [comment]
I implemented your suggestion in pull request #74

**Comment by abauville** [comment]
I implemented your suggestion in pull request https://github.com/abauville/lickwars/pull/75
